before_install:
  - printenv
env:
  - IMAGE_NAME="$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f2)"  
services:
  - docker
before_script:
  - docker run --rm -v $(pwd):/app composer install
script:
  - docker build -t "${IMAGE_NAME}" .
  - docker run --rm -v $(pwd):/var/www/html "${IMAGE_NAME}" vendor/bin/phpunit