version: '3.6'

services:
  php:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - mysql   
    networks: ['app-stack']

  php-worker:
    container_name: worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
    command: php artisan queue:work redis  
    depends_on:
      - mysql
      - redis   
    networks: ['app-stack']    

  nginx:
    container_name: app-nginx
    image: nginx:1.15-alpine-perl
    restart: always
    volumes:
      - "./dockers/app.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
    depends_on:
      - php
    ports:
      - 8082:80
    networks: ['app-stack']  

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: redis-server
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    depends_on:
      - php
    networks: ['app-stack'] 
    
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 33060:3306
    networks: ['app-stack']  
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw
      MYSQL_DATABASE: app_db
      MYSQL_USER: app
      MYSQL_PASSWORD: mysecret_dev_pass  

networks: {app-stack: {}}
volumes:
  redis-data: 
  mysql-data:        